language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g npm
  - npm install -g bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test -- karma.conf-ci.js
after-script:
  - cat ./coverage/PhantomJS*/lcov.info | .node_modules/codeclimate-test-reporter/bin/codeclimate.js
env:
  global:
    - secure: NaypVJarWV4WxN0BFrQibTuHq+XtlIKrYDXBuDILwCarElUYK+Likg+Fg50idg3ZgRRPz1qFDH3NewhjbiEvtrGlHw1BCKFnOuBiDyb8KxIzcFoAPCWYXS8owfsrrgGNwLb7Q4t7YW5IWNhx6gJR4DHwP/KsPaqNoZBZoKGwxRM=
    - secure: lt1pwoihBwK6iLD48sxxEf+rN9a0z49/Bd5GLh3P8qUw1mILA+jHVLyjLok3YvffiZy4LNnMJrK2mGHKwGOa+fWSBt2PgHmSyDogT8HEtOExtphHcK0uzmstkzJbrYnC2DRstikxX3aXKHUKUsc0e0PjjMOpsoZlHye7Fk+GNqE=
    - secure: enRVqsy69j9GQ5xEpfEhlhCqm1/W5vxa/5nVCGVzEfe/8NOo7S6yw+XARAJpjEID+rjPmztFjhbRg3jLt0k1nMcU8SKtKB/oX9lRKXUBcigmmImnHCASpnXR8QDSb8/oa+CNIbMbOvC3nKQaUISnQMfxh/i7kzvqy6e6urH+9ng=
    - secure: PAt3CXnaFIBo8K26gpN0voKb3colidWJZPCwNy3bYtM5AyZCR1Pcsu8H8o0LRbpC83xkDWscuESmNpJS+uvoqHnbmxoCFtZaYVwYgUQJnY0jJoQawqgaK+fxVGqz3T2IYI01eQQa/xyNWbmKtEJoDK0zsXBB6PWSgEOaj4IlwQM=
